# render.yaml (VERSÃO CORRIGIDA E AJUSTADA)
# Receita para implantar a Evolution API no Render.com

# Primeiro, definimos os "recursos" que vamos usar, como discos.
disks:
  - name: evolution-data      # Nome do nosso "HD externo virtual"
    sizeGB: 1                 # 1 GB é mais que suficiente
    
# Agora, definimos os serviços que usarão esses recursos.
services:
  # Define o serviço principal, que será a nossa API
  - type: web
    name: evolution-api       # Nome do seu serviço no painel do Render
    image: atende/evolution-api:latest   # Imagem oficial da Evolution API no Docker Hub

    # --- Configuração do Disco Persistente ---
    disks:
      - name: evolution-data    # Usa o disco com este nome
        mountPath: /evolution/instances # Onde o disco será "conectado" dentro do contêiner
      
    # --- Configuração de Rede e Saúde ---
    envVars:
      - key: PORT
        value: 8080

    healthCheckPath: /

    # --- Plano de Assinatura ---
    plan: free
