services:
- type: web
name: evolution-api
env: docker
repo: https://github.com/EvolutionAPI/evolution-api
branch: main
autoDeploy: false
envVars:
  - key: PORT
    value: 8080
  - key: DATABASE_ENABLED
    value: false
disks:
  - name: evolution-data
    mountPath: /evolution/dist/instances
    sizeGB: 1
plan: free

