services:
  - type: web
    name: evolution-api
    plan: free
    env: docker
    image: atende/evolution-api:latest

    envVars:
      - key: PORT
        value: 8080

    healthCheckPath: /
